# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f174ff3bccdd8929d4ae11cc2ca397f25fb75928d6cf0ab846830e2327ac463600674bfe57db56df8e9603a81851a629f001b31cf7b0c7d8c3866ffea76e8db0

test:
  secret_key_base: 376ed10d127587587a064d6bf12cad12dbc225c16ffb73c1c2b7b0f8b090c0edfd7699ec1152604eaa4c2104de4e4e3e94ebda2ed6bc2806f4317b3c474616b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
